name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore ./test/test.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./test/test.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal ./test/test.sln
