name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Specify the version you are using

    - name: Restore dependencies
      run: dotnet restore OOP.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore OOP.sln

    - name: Run tests
      run: dotnet test --no-build --verbosity normal OOP.sln
